Read data from .txt file for propulsion
Also, (slightly dated) additions to the main and the dynamics.
Summary below:

rtraj: Added some more scripts to utilize the cache when loading the
       Earth model and propulsion data. Tried adding more inputs, but
       didn't get too far. Also, changed flags from the 'flag_*' pattern
       to a structure contained within 'flags' (not in rtraj itself,
       but the flags go to the rtraj workspace from the scripts)

loadPropulsionData: Fully working cache now and ability to read
                    (custom) files used to define parameters related to
                    the vehicle's propulsion system (thrust). Still need
                    to work on reading data for mass flow, etc., but
                    this task is considerably easier than what's already
                    been done (just need to read a .csv, not parse
                    through text).

refPropulsionCache: Properly functioning cache system now. Also,
                    changed flags to reflect the new structure in main.

readThrustProfile: Text file parser to read custom formatted propulsion
                   files that will be used to provide inputs for
                   simulation.

getNumberOfLines: Count the number of (remaining) lines in a file. This
                  behavior will be changed later to count all of the
                  lines in a file and perhaps reset the head back to
                  where it started.

issueReadError: Very simple function that just preformats an error
                message for when something goes wrong in reading the
                propulsion parameter files.

finalizeInputs: Added Tenv_rail transformation to express the initial
                position and velocity correctly in the ENV frame.

odeval: Added a significant amount of new sections, transformations,
        etc. Most newly added sections aren't complete, but a
        transformation was found to rotate coordinates from the body-
        fixed frame to the velocity frame using the angle of attack and
        a "velocity roll" angle.

.gitignore: Continued moving some files around, so changes reflected
            here. Also fixed some issue with ignoring the wrong folder.